// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: catalogservice/catalog_service.proto

package catalogservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CatalogService_ResolveTree_FullMethodName                    = "/catalogservice.CatalogService/ResolveTree"
	CatalogService_ListResources_FullMethodName                  = "/catalogservice.CatalogService/ListResources"
	CatalogService_RemoveTarget_FullMethodName                   = "/catalogservice.CatalogService/RemoveTarget"
	CatalogService_DeleteResource_FullMethodName                 = "/catalogservice.CatalogService/DeleteResource"
	CatalogService_WatchTree_FullMethodName                      = "/catalogservice.CatalogService/WatchTree"
	CatalogService_GetEntityManifest_FullMethodName              = "/catalogservice.CatalogService/GetEntityManifest"
	CatalogService_ListEntitiesByCrossplaneSource_FullMethodName = "/catalogservice.CatalogService/ListEntitiesByCrossplaneSource"
)

// CatalogServiceClient is the client API for CatalogService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogServiceClient interface {
	// ResolveTree returns the full catalog graph rooted at the given URL.
	ResolveTree(ctx context.Context, in *ResolveTreeRequest, opts ...grpc.CallOption) (*ResolveTreeResponse, error)
	// ListResources returns a flat list of all non-Location entities.
	ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error)
	// RemoveTarget removes a target from a location.yaml via PR.
	RemoveTarget(ctx context.Context, in *RemoveTargetRequest, opts ...grpc.CallOption) (*RemoveTargetResponse, error)
	// DeleteResource deletes a resource from Git and removes the
	// referring target from its parent location in a single PR.
	DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error)
	// WatchTree replays the current tree as ADDED events, then streams
	// diffs against successive poll snapshots until the client leaves.
	WatchTree(ctx context.Context, in *WatchTreeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TreeEvent], error)
	// GetEntityManifest returns the Crossplane Claim/XR manifests
	// linked from a catalog entity via the
	// machinery.stuttgart-things.com/crossplane-* annotations.
	GetEntityManifest(ctx context.Context, in *GetEntityManifestRequest, opts ...grpc.CallOption) (*GetEntityManifestResponse, error)
	// ListEntitiesByCrossplaneSource is the reverse of
	// GetEntityManifest: given a Crossplane manifest URL, return the
	// catalog entities whose annotations reference it.
	ListEntitiesByCrossplaneSource(ctx context.Context, in *ListEntitiesByCrossplaneSourceRequest, opts ...grpc.CallOption) (*ListEntitiesByCrossplaneSourceResponse, error)
}

type catalogServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogServiceClient(cc grpc.ClientConnInterface) CatalogServiceClient {
	return &catalogServiceClient{cc}
}

func (c *catalogServiceClient) ResolveTree(ctx context.Context, in *ResolveTreeRequest, opts ...grpc.CallOption) (*ResolveTreeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveTreeResponse)
	err := c.cc.Invoke(ctx, CatalogService_ResolveTree_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListResources(ctx context.Context, in *ListResourcesRequest, opts ...grpc.CallOption) (*ListResourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResourcesResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListResources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) RemoveTarget(ctx context.Context, in *RemoveTargetRequest, opts ...grpc.CallOption) (*RemoveTargetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveTargetResponse)
	err := c.cc.Invoke(ctx, CatalogService_RemoveTarget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) DeleteResource(ctx context.Context, in *DeleteResourceRequest, opts ...grpc.CallOption) (*DeleteResourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResourceResponse)
	err := c.cc.Invoke(ctx, CatalogService_DeleteResource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) WatchTree(ctx context.Context, in *WatchTreeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TreeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CatalogService_ServiceDesc.Streams[0], CatalogService_WatchTree_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTreeRequest, TreeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CatalogService_WatchTreeClient = grpc.ServerStreamingClient[TreeEvent]

func (c *catalogServiceClient) GetEntityManifest(ctx context.Context, in *GetEntityManifestRequest, opts ...grpc.CallOption) (*GetEntityManifestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEntityManifestResponse)
	err := c.cc.Invoke(ctx, CatalogService_GetEntityManifest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogServiceClient) ListEntitiesByCrossplaneSource(ctx context.Context, in *ListEntitiesByCrossplaneSourceRequest, opts ...grpc.CallOption) (*ListEntitiesByCrossplaneSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEntitiesByCrossplaneSourceResponse)
	err := c.cc.Invoke(ctx, CatalogService_ListEntitiesByCrossplaneSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServiceServer is the server API for CatalogService service.
// All implementations must embed UnimplementedCatalogServiceServer
// for forward compatibility.
type CatalogServiceServer interface {
	// ResolveTree returns the full catalog graph rooted at the given URL.
	ResolveTree(context.Context, *ResolveTreeRequest) (*ResolveTreeResponse, error)
	// ListResources returns a flat list of all non-Location entities.
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	// RemoveTarget removes a target from a location.yaml via PR.
	RemoveTarget(context.Context, *RemoveTargetRequest) (*RemoveTargetResponse, error)
	// DeleteResource deletes a resource from Git and removes the
	// referring target from its parent location in a single PR.
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	// WatchTree replays the current tree as ADDED events, then streams
	// diffs against successive poll snapshots until the client leaves.
	WatchTree(*WatchTreeRequest, grpc.ServerStreamingServer[TreeEvent]) error
	// GetEntityManifest returns the Crossplane Claim/XR manifests
	// linked from a catalog entity via the
	// machinery.stuttgart-things.com/crossplane-* annotations.
	GetEntityManifest(context.Context, *GetEntityManifestRequest) (*GetEntityManifestResponse, error)
	// ListEntitiesByCrossplaneSource is the reverse of
	// GetEntityManifest: given a Crossplane manifest URL, return the
	// catalog entities whose annotations reference it.
	ListEntitiesByCrossplaneSource(context.Context, *ListEntitiesByCrossplaneSourceRequest) (*ListEntitiesByCrossplaneSourceResponse, error)
	mustEmbedUnimplementedCatalogServiceServer()
}

// UnimplementedCatalogServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServiceServer struct{}

func (UnimplementedCatalogServiceServer) ResolveTree(context.Context, *ResolveTreeRequest) (*ResolveTreeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveTree not implemented")
}
func (UnimplementedCatalogServiceServer) ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListResources not implemented")
}
func (UnimplementedCatalogServiceServer) RemoveTarget(context.Context, *RemoveTargetRequest) (*RemoveTargetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTarget not implemented")
}
func (UnimplementedCatalogServiceServer) DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteResource not implemented")
}
func (UnimplementedCatalogServiceServer) WatchTree(*WatchTreeRequest, grpc.ServerStreamingServer[TreeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchTree not implemented")
}
func (UnimplementedCatalogServiceServer) GetEntityManifest(context.Context, *GetEntityManifestRequest) (*GetEntityManifestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntityManifest not implemented")
}
func (UnimplementedCatalogServiceServer) ListEntitiesByCrossplaneSource(context.Context, *ListEntitiesByCrossplaneSourceRequest) (*ListEntitiesByCrossplaneSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEntitiesByCrossplaneSource not implemented")
}
func (UnimplementedCatalogServiceServer) mustEmbedUnimplementedCatalogServiceServer() {}
func (UnimplementedCatalogServiceServer) testEmbeddedByValue()                        {}

// UnsafeCatalogServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServiceServer will
// result in compilation errors.
type UnsafeCatalogServiceServer interface {
	mustEmbedUnimplementedCatalogServiceServer()
}

func RegisterCatalogServiceServer(s grpc.ServiceRegistrar, srv CatalogServiceServer) {
	// If the following call panics, it indicates UnimplementedCatalogServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CatalogService_ServiceDesc, srv)
}

func _CatalogService_ResolveTree_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveTreeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ResolveTree(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ResolveTree_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ResolveTree(ctx, req.(*ResolveTreeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListResourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListResources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListResources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListResources(ctx, req.(*ListResourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_RemoveTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).RemoveTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_RemoveTarget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).RemoveTarget(ctx, req.(*RemoveTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_DeleteResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteResourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).DeleteResource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_DeleteResource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).DeleteResource(ctx, req.(*DeleteResourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_WatchTree_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTreeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CatalogServiceServer).WatchTree(m, &grpc.GenericServerStream[WatchTreeRequest, TreeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CatalogService_WatchTreeServer = grpc.ServerStreamingServer[TreeEvent]

func _CatalogService_GetEntityManifest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntityManifestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).GetEntityManifest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_GetEntityManifest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).GetEntityManifest(ctx, req.(*GetEntityManifestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CatalogService_ListEntitiesByCrossplaneSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEntitiesByCrossplaneSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServiceServer).ListEntitiesByCrossplaneSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CatalogService_ListEntitiesByCrossplaneSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServiceServer).ListEntitiesByCrossplaneSource(ctx, req.(*ListEntitiesByCrossplaneSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CatalogService_ServiceDesc is the grpc.ServiceDesc for CatalogService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CatalogService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "catalogservice.CatalogService",
	HandlerType: (*CatalogServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveTree",
			Handler:    _CatalogService_ResolveTree_Handler,
		},
		{
			MethodName: "ListResources",
			Handler:    _CatalogService_ListResources_Handler,
		},
		{
			MethodName: "RemoveTarget",
			Handler:    _CatalogService_RemoveTarget_Handler,
		},
		{
			MethodName: "DeleteResource",
			Handler:    _CatalogService_DeleteResource_Handler,
		},
		{
			MethodName: "GetEntityManifest",
			Handler:    _CatalogService_GetEntityManifest_Handler,
		},
		{
			MethodName: "ListEntitiesByCrossplaneSource",
			Handler:    _CatalogService_ListEntitiesByCrossplaneSource_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchTree",
			Handler:       _CatalogService_WatchTree_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "catalogservice/catalog_service.proto",
}
